package com.data.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.data.greendao.User;
import com.data.greendao.Channel;
import com.data.greendao.Task;
import com.data.greendao.Note;
import com.data.greendao.Activity;

import com.data.greendao.UserDao;
import com.data.greendao.ChannelDao;
import com.data.greendao.TaskDao;
import com.data.greendao.NoteDao;
import com.data.greendao.ActivityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig channelDaoConfig;
    private final DaoConfig taskDaoConfig;
    private final DaoConfig noteDaoConfig;
    private final DaoConfig activityDaoConfig;

    private final UserDao userDao;
    private final ChannelDao channelDao;
    private final TaskDao taskDao;
    private final NoteDao noteDao;
    private final ActivityDao activityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        channelDaoConfig = daoConfigMap.get(ChannelDao.class).clone();
        channelDaoConfig.initIdentityScope(type);

        taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        activityDaoConfig = daoConfigMap.get(ActivityDao.class).clone();
        activityDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        channelDao = new ChannelDao(channelDaoConfig, this);
        taskDao = new TaskDao(taskDaoConfig, this);
        noteDao = new NoteDao(noteDaoConfig, this);
        activityDao = new ActivityDao(activityDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Channel.class, channelDao);
        registerDao(Task.class, taskDao);
        registerDao(Note.class, noteDao);
        registerDao(Activity.class, activityDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        channelDaoConfig.getIdentityScope().clear();
        taskDaoConfig.getIdentityScope().clear();
        noteDaoConfig.getIdentityScope().clear();
        activityDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ChannelDao getChannelDao() {
        return channelDao;
    }

    public TaskDao getTaskDao() {
        return taskDao;
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public ActivityDao getActivityDao() {
        return activityDao;
    }

}
