package com.data.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TASK.
 */
public class Task {

    private Long id;
    private String title;
    private String due_at;
    private String state;
    private Integer user_id;
    private Integer assigned_user_id;
    private Integer channel_id;
    private String do_at;
    private String done_at;
    private String created_at;

    public Task() {
    }

    public Task(Long id) {
        this.id = id;
    }

    public Task(Long id, String title, String due_at, String state, Integer user_id, Integer assigned_user_id, Integer channel_id, String do_at, String done_at, String created_at) {
        this.id = id;
        this.title = title;
        this.due_at = due_at;
        this.state = state;
        this.user_id = user_id;
        this.assigned_user_id = assigned_user_id;
        this.channel_id = channel_id;
        this.do_at = do_at;
        this.done_at = done_at;
        this.created_at = created_at;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDue_at() {
        return due_at;
    }

    public void setDue_at(String due_at) {
        this.due_at = due_at;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public Integer getUser_id() {
        return user_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    public Integer getAssigned_user_id() {
        return assigned_user_id;
    }

    public void setAssigned_user_id(Integer assigned_user_id) {
        this.assigned_user_id = assigned_user_id;
    }

    public Integer getChannel_id() {
        return channel_id;
    }

    public void setChannel_id(Integer channel_id) {
        this.channel_id = channel_id;
    }

    public String getDo_at() {
        return do_at;
    }

    public void setDo_at(String do_at) {
        this.do_at = do_at;
    }

    public String getDone_at() {
        return done_at;
    }

    public void setDone_at(String done_at) {
        this.done_at = done_at;
    }

    public String getCreated_at() {
        return created_at;
    }

    public void setCreated_at(String created_at) {
        this.created_at = created_at;
    }

}
